### ISSUE TITLE
Can‘t run this code

### ISSUE THREAD

**Issue by SouthWindShiB** [laituan245/rescnn_bioel#1]
I have read the paper, it's a interesting work. But I can't run this code withought a guildline.

When the detailed  readme will be release? and those processed .json file?

**Comment by laituan245** [comment]
Thank you for your interest. I will release the detailed running instructions in 2-3 weeks. I am working on some other deadlines at the moment. Sorry for the delay.

**Comment by laituan245** [comment]
I realized that after uploading the datasets, it is not difficult to run the current code.

Please check the updated README. Basically, you would just need to install the dependencies and then run `python cg_trainer.py`. 

Please let me know if there is any problem.

**Comment by SouthWindShiB** [comment]
Thanks for your reply,

I can't run this code for BC5CDR datasets, Because there is some difference between your code and the downloaded data(from BioSyn).

In your code, I need the .json file to initialize the Ontology class, but the downloaded data dosen't have .json file

Can you upload these files, or release the script to process the existing .txt and .concept files to get those .json.

Sorry to bother~

![image](https://user-images.githubusercontent.com/33797295/142734386-fbc11fff-677c-4842-ab55-58d3797f3325.png)
![image](https://user-images.githubusercontent.com/33797295/142734395-1b280a73-b509-481f-8f43-1d60ac2206ae.png)
