### ISSUE TITLE
Some files are still missing

### ISSUE THREAD

**Issue by SouthWindShiB** [laituan245/rescnn_bioel#2]
Thanks for your reply,  #1 

I can't run this code for BC5CDR datasets, Because there is some difference between your code and the downloaded data(from BioSyn).

In your code, I need the .json file to initialize the Ontology class, but the downloaded data dosen't have .json file

Can you upload these files, or release the script to process the existing .txt and .concept files to get those .json.

Sorry to bother~

![image](https://user-images.githubusercontent.com/33797295/142734507-c92ac740-d5e9-45a6-b601-7026366a62cd.png)

![image](https://user-images.githubusercontent.com/33797295/142734561-b3b8b693-c465-4080-aea2-e52a04385254.png)

![image](https://user-images.githubusercontent.com/33797295/142734512-925c9044-4e2b-49c6-9872-60be9daa1a2a.png)

**Comment by laituan245** [comment]
I already provided those files in this repo: https://github.com/laituan245/rescnn_bioel/tree/main/resources?

I am not sure what is your problem. Could you share the error message when running the code?

**Comment by laituan245** [comment]
Also unrelated to your issue, you may want to download the pretrained token embedding layer (https://github.com/laituan245/rescnn_bioel/commit/90d292bc2e474bdd75baf4f428d9034e1d462219). The code will still run without it. But using the pretrained embedding layer from PubmedBERT is needed for better performance.
