### ISSUE TITLE
umls ontology preprocess

### ISSUE THREAD

**Issue by Annztt** [laituan245/rescnn_bioel#3]
Dear author, 

Thanks for making the code publicly available! 

However, I still have some problems in running code on the MedMentions dataset because of the lack of UMLS 2017aa ontology file. I have downloaded the UMLS-2017aa-full file and installed it on my device. And the number of unique concepts in it is 3,415,665, the number of unique synonyms of all concepts in it is 7,135,041.But my experimental results of acc@1 on the MedMentions test set is 80%+, which is much higher than the results reported in your paper. 

Is there something wrong with me when dealing with umls-2017aa-full?

**Comment by laituan245** [comment]
Hi. Thank you for your interest. If possible, could you let me know your email address? Due to the UMLS licensing issue, I probably cannot publicly upload my ontology file here. I can send it to you by email. My email is tuanml2@illinois.edu
