### ISSUE TITLE
Cannot reproduce results on NCBI-Diseases

### ISSUE THREAD

**Issue by GanjinZero** [laituan245/rescnn_bioel#4]
I have downloaded embedding.pt and use
```
python cg_trainer.py --dataset ncbi-disease
```
to train NCBI-D.

I obtain results of {'top1_accuracy': 0.90833, 'top5_accuracy': 0.93958, 'top10_accuracy': 0.95625, 'top20_accuracy': 0.96042} which is lower than your reported 92.4.
Do I miss something to reproduce your results.

**Comment by GanjinZero** [comment]
Results of another run:
{'top1_accuracy': 0.91667, 'top5_accuracy': 0.94688, 'top10_accuracy': 0.95208, 'top20_accuracy': 0.96042}

**Comment by laituan245** [comment]
Probably it is worth tuning the number of epochs. I will try training the model again in the near future. Let me know if you need the trained checkpoints.

**Comment by GanjinZero** [comment]
> Probably it is worth tuning the number of epochs. I will try training the model again in the near future. Let me know if you need the trained checkpoints.

Thanks for your reply. I want the hypermeters you trained for NCBI and checkpoints.

**Comment by laituan245** [comment]
Trained checkpoint: https://drive.google.com/file/d/1JGCdFLKTsEoQ7HtslO47VjkymPytDgy_/view?usp=sharing

The hyper-parameters are all in the config file. But I used different number of epochs for different datasets. I do not remember them at the moment. So it may be worth tuning the number of epochs. I will try to retrain the models in the future.

**Comment by laituan245** [comment]
After downloading the ckpt, please set the path here https://github.com/laituan245/rescnn_bioel/blob/main/cg_trainer.py#L24

Results:
```
Test results: {'top1_accuracy': 0.92396, 'top5_accuracy': 0.94479, 'top10_accuracy': 0.95104, 'top20_accuracy': 0.95625}
continue?Prepared the optimizer and the scheduler
```

**Comment by GanjinZero** [comment]
thank you!
