### ISSUE TITLE
Will running instructions being provided in the future?

### ISSUE THREAD

**Issue by teohsinyee** [laituan245/rescnn_bioel#6]

**Comment by laituan245** [comment]
I believe the README file already has the running instructions. Please let me know if you have any specific problem.

**Comment by teohsinyee** [comment]
> I believe the README file already has the running instructions. Please let me know if you have any specific problem.

Oh there are basic running instructions. 
Because I saw a line in README  '`We are cleaning the codebase and we will add more running instructions soon.`'

Just to check if this repo is still in maintenance or not :)
